### ISSUE TITLE
Separate color theme configs

### ISSUE THREAD

**Issue by fox0430** [fox0430/moe#1971]
### Detailed Description

- Remove color configs from `Theme` table in`moerc.toml`
- Add `path` to `Theme` table. The path to the color config

## Example

moerc.toml
```toml
[Theme]
path = "~/.config/moe/themes/dark.toml"
```

dark.toml
```toml
[Colors]
foreground = "#ffffff"
background = "#000000"

lineNum = "#ffffff"
```
